/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Index;

import Cliente.Cliente;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import Login.Login;
import Refacciones.Refacciones;

/**
 *
 * @author roy_b
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Consultar() {
        initComponents();
         this.setLocationRelativeTo(null); //Poner el form en el centro
        
   Border panel_log =BorderFactory.createMatteBorder(5, 5, 1, 1,Color.black);
   jPanel1_ind.setBorder(panel_log);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jengi = new javax.swing.JToggleButton();
        Jengi2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1_ind = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Cliente = new javax.swing.JButton();
        jLabelmin = new javax.swing.JLabel();
        jLabelcerrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();
        jButton_refacciones = new javax.swing.JButton();

        Jengi.setText("jToggleButton1");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Jengi2.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1_ind.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cservicios1.png"))); // NOI18N

        jButton_Cliente.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cliente.setText("Consultar Cliente");
        jButton_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseExited(evt);
            }
        });
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });

        jLabelmin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });

        jLabelcerrar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelcerrar.setText("x");
        jLabelcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcerrarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cerrar sesión");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        jButton_volver.setBackground(new java.awt.Color(192, 57, 43));
        jButton_volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });

        jButton_refacciones.setBackground(new java.awt.Color(34, 167, 240));
        jButton_refacciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_refacciones.setText("Consultar Refacciones");
        jButton_refacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_refaccionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_refaccionesMouseExited(evt);
            }
        });
        jButton_refacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refaccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_indLayout = new javax.swing.GroupLayout(jPanel1_ind);
        jPanel1_ind.setLayout(jPanel1_indLayout);
        jPanel1_indLayout.setHorizontalGroup(
            jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_indLayout.createSequentialGroup()
                                .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_indLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(49, 49, 49))))
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton_Cliente)
                        .addGap(54, 54, 54)
                        .addComponent(jButton_refacciones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton_volver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1_indLayout.setVerticalGroup(
            jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_refacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addComponent(jButton_volver, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
         Login form = new Login();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //Cerra el formulario actual
                this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        if(evt.isPopupTrigger())
        {
            Jengi2.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcerrarMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelcerrarMouseClicked

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
        Cliente C= new Cliente();
        C.setVisible(true);
        C.pack();
        C.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jButton_ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseExited
        jButton_Cliente.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_ClienteMouseExited

    private void jButton_ClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseEntered
        jButton_Cliente.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_ClienteMouseEntered

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        Index I = new Index();
        I.setVisible(true);
        I.pack();
        I.setLocationRelativeTo(null);
        //Cerra el formulario actual
        this.dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_refaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_refaccionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_refaccionesMouseEntered

    private void jButton_refaccionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_refaccionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_refaccionesMouseExited

    private void jButton_refaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refaccionesActionPerformed
        Refacciones R= new Refacciones();
        R.setVisible(true);
        R.pack();
        R.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_jButton_refaccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Jengi;
    private javax.swing.JPopupMenu Jengi2;
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_refacciones;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelcerrar;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1_ind;
    // End of variables declaration//GEN-END:variables
}
