/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Index;

import Cliente.RegistroC;
import Empleados.Empleados;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import Login.Login;
import Reportes.Reportes;
import Servicio.Servicio;

/**
 *
 * @author roy_b
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Registro() {
        initComponents();
         this.setLocationRelativeTo(null); //Poner el form en el centro
        
   Border panel_log =BorderFactory.createMatteBorder(5, 5, 1, 1,Color.black);
   jPanel1_ind.setBorder(panel_log);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jengi = new javax.swing.JToggleButton();
        Jengi2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1_ind = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_ref = new javax.swing.JButton();
        jButton_Cliente = new javax.swing.JButton();
        jButton_emp = new javax.swing.JButton();
        jButton_rep = new javax.swing.JButton();
        jButton_pro = new javax.swing.JButton();
        jLabelmin = new javax.swing.JLabel();
        jLabelcerrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();

        Jengi.setText("jToggleButton1");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Jengi2.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1_ind.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cservicios1.png"))); // NOI18N

        jButton_ref.setBackground(new java.awt.Color(34, 167, 240));
        jButton_ref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ref.setText("Registar Refacciones");
        jButton_ref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_refMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_refMouseExited(evt);
            }
        });

        jButton_Cliente.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cliente.setText("Registrar cliente");
        jButton_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseExited(evt);
            }
        });
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });

        jButton_emp.setBackground(new java.awt.Color(34, 167, 240));
        jButton_emp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_emp.setText("Regstrar personal");
        jButton_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_empMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_empMouseExited(evt);
            }
        });
        jButton_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empActionPerformed(evt);
            }
        });

        jButton_rep.setBackground(new java.awt.Color(34, 167, 240));
        jButton_rep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_rep.setText("Registar Servicio");
        jButton_rep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_repMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_repMouseExited(evt);
            }
        });
        jButton_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_repActionPerformed(evt);
            }
        });

        jButton_pro.setBackground(new java.awt.Color(34, 167, 240));
        jButton_pro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_pro.setText("Registar  equipo");
        jButton_pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_proMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_proMouseExited(evt);
            }
        });

        jLabelmin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelmin.setText("-");
        jLabelmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelminMouseClicked(evt);
            }
        });

        jLabelcerrar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelcerrar.setText("x");
        jLabelcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcerrarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cerrar sesión");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        jButton_volver.setBackground(new java.awt.Color(192, 57, 43));
        jButton_volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver.setText("Volver");
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_indLayout = new javax.swing.GroupLayout(jPanel1_ind);
        jPanel1_ind.setLayout(jPanel1_indLayout);
        jPanel1_indLayout.setHorizontalGroup(
            jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_indLayout.createSequentialGroup()
                                .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_indLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(49, 49, 49))))
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_indLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jButton_Cliente)
                                .addGap(57, 57, 57)
                                .addComponent(jButton_emp))
                            .addGroup(jPanel1_indLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jButton_ref)))
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1_indLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButton_pro))
                            .addGroup(jPanel1_indLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton_rep)))
                        .addContainerGap(114, Short.MAX_VALUE))))
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton_volver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1_indLayout.setVerticalGroup(
            jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_indLayout.createSequentialGroup()
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_indLayout.createSequentialGroup()
                        .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1_indLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_rep, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton_volver, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_ind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
               RegistroC form = new RegistroC();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                
                this.dispose(); 
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jLabelminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelminMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelminMouseClicked

    private void jLabelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcerrarMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabelcerrarMouseClicked

    private void jButton_ClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseEntered
       jButton_Cliente.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_ClienteMouseEntered

    private void jButton_ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseExited
         jButton_Cliente.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_ClienteMouseExited

    private void jButton_empMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_empMouseEntered
         jButton_emp.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_empMouseEntered

    private void jButton_empMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_empMouseExited
        jButton_emp.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_empMouseExited

    private void jButton_proMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_proMouseEntered
       jButton_pro.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_proMouseEntered

    private void jButton_proMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_proMouseExited
       jButton_pro.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_proMouseExited

    private void jButton_refMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_refMouseEntered
        jButton_ref.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_refMouseEntered

    private void jButton_refMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_refMouseExited
         jButton_ref.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_refMouseExited

    private void jButton_repMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_repMouseEntered
         jButton_rep.setBackground(new Color(34,167,240));
    }//GEN-LAST:event_jButton_repMouseEntered

    private void jButton_repMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_repMouseExited
        jButton_rep.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton_repMouseExited

    private void jButton_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empActionPerformed
        Empleados form = new Empleados();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //Cerra el formulario actual
                this.dispose();
    }//GEN-LAST:event_jButton_empActionPerformed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        if(evt.isPopupTrigger())
        {
           Jengi2.show(evt.getComponent(),evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
         Login form = new Login();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //Cerra el formulario actual
                this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_repActionPerformed
         Reportes form = new Reportes();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                
                this.dispose(); 
    }//GEN-LAST:event_jButton_repActionPerformed

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        Index I = new Index();
        I.setVisible(true);
        I.pack();
        I.setLocationRelativeTo(null);
        //Cerra el formulario actual
        this.dispose();
    }//GEN-LAST:event_jButton_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Jengi;
    private javax.swing.JPopupMenu Jengi2;
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_emp;
    private javax.swing.JButton jButton_pro;
    private javax.swing.JButton jButton_ref;
    private javax.swing.JButton jButton_rep;
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelcerrar;
    private javax.swing.JLabel jLabelmin;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1_ind;
    // End of variables declaration//GEN-END:variables
}
